server:
  port: 9000
spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: bhPFP8kW9nhPGuiAe7KRJIGkEqW6nkAu
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/microservices
  cloud:
    gateway:
      routes:
        - id: product-ms
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - TokenRelay= #repassa o token para todas as apis
