server:
  port: 9000
spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: bhPFP8kW9nhPGuiAe7KRJIGkEqW6nkAu
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/microservices
  cloud:
    gateway:
      # Usar rotas sem eureka
      # routes:
      #   - id: product-ms
      #     uri: http://localhost:8081
      #     predicates:
      #       - Path=/products/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
          # filters:
          #   - TokenRelay= #repassa o token para todas as apis

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
